# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testchar <- function(type) {
    .Call(`_quantpack_testchar`, type)
}

#' Black-Scholes Function returning euro option prices
#' Supports vectors in Rcpp for loop
#'
#' @param S, Spot security price
#' @param K, Strike price
#' @param T, Time to maturity, fractional years
#' @param r, Risk-free interest rate
#' @param sig Sigma, option yearly volatility
#' @param type Option type "C" or "P"
#' @return option value scalar
#' @export
calc_bs_cpp_loop <- function(S, K, T, R, sig, type) {
    .Call(`_quantpack_calc_bs_cpp_loop`, S, K, T, R, sig, type)
}

#' Black-Scholes Function returning euro option prices
#' Supports vectors in Rcpp with vectorized calculation
#'
#' @param S, Spot security price
#' @param K, Strike price
#' @param T, Time to maturity, fractional years
#' @param r, Risk-free interest rate
#' @param sig Sigma, option yearly volatility
#' @param type Option type "C" or "P"
#' @return option value scalar
#' @export
calc_bs_cpp <- function(S, K, T, R, sig, type) {
    .Call(`_quantpack_calc_bs_cpp`, S, K, T, R, sig, type)
}

#' Numerical computation of options implied volatility using BS
#' Supports vectors
#'
#' @param S, Spot security price
#' @param K, Strike price
#' @param T, Time to maturity, fractional years
#' @param r, Risk-free interest rate
#' @param market Market price
#' @param type Option type "C" or "P"
#' @return Option implied yearly volatility
#' @export
calc_bs_iv_cpp <- function(S, K, T, r, market, op_type) {
    .Call(`_quantpack_calc_bs_iv_cpp`, S, K, T, r, market, op_type)
}

#' Rolling percentile
#'
#' @param x, vector of feature
#' @param n, window size
#' @param na_rm, to remove NA's or not
#' @export
calc_rolling_percentile <- function(x, n, na_rm = TRUE) {
    .Call(`_quantpack_calc_rolling_percentile`, x, n, na_rm)
}

